### ISSUE TITLE
Can't load font 

### ISSUE THREAD

**Issue by duichwer** [OkunaOrg/okuna-www#123]
I was inspecting the website and got the following loading error.
I receive this error on different browsers.

Maybe it can be solved with something in the [server config](https://stackoverflow.com/a/35898578).

![grafik](https://user-images.githubusercontent.com/16852427/62896535-8dc4db00-bd51-11e9-9249-b238d187d738.png)

**Comment by duichwer** [comment]
Maybe i found the reason for this issue.
There isn't a file called "nunito\*-latin-600\*".
https://github.com/OkunaOrg/okuna-www/blob/84ba81dc85f9373f7d44bde5250095e7cf2b8d9e/src/styles/lib/_font.scss#L17

There ar only files "nunito\*-latin-regular\*" and  "nunito\*-latin-700\*".

Since I'm not sure which one should be used for the font-face a PR is difficult for me.

**Comment by jozsefsallai** [comment]
Closing since this was fixed by #128.
