### ISSUE TITLE
Translation of About-Us

### ISSUE THREAD

**Issue by flogruber** [OkunaOrg/okuna-www#141]
If the language is changed via the language dropdown, the jobtitle and the description of the team-members and the ambassadors are not changed to the selected language, the loaded language remains.

## Step to reproduce:

1. Open [About-Us](https://www.okuna.io/en/about-us)
2. The jobtitles and descriptions are displayed in *en* 
3. Now switch to another language via the dropdown e.g. *de*
4. The entire page will be translated into german, but the jobdescription and the description will still be displayed in *en*

**Comment by Komposten** [comment]
The titles and descriptions are translated correctly if you go directly to a translated page (e.g. https://www.okuna.io/de/about-us), so it must be the "hot swap" of the language that isn't working.

**Comment by jozsefsallai** [comment]
Looks like something that can be solved by turning the members array into a computed property (currently, the array is in the data() initializer). Will look into this tomorrow.
