### ISSUE TITLE
Is this a social network website or just a marketing page for one

### ISSUE THREAD

**Issue by alsiPanda** [OkunaOrg/okuna-www#147]
Hi, 
I stumbled across okuna searching for an open source social network, upon which i could build one of my own. I cloned and installed okuna as a test and the home page looked neat. But when i went in deep into the files, I couldn't find anything remotely like a social network. Now I am an amateur so I decided to ask here, Am I looking in the wrong repo or has okuna not been built yet ? Is the code hosted here just for marketing purposes etc ?

**Comment by jozsefsallai** [comment]
Hello!

https://www.okuna.io is the landing page of the Okuna social network, which is currently available as a mobile app. The website and this repo are not the social network, however, a web version of Okuna is currently in works and should be out in the future!

You should check out the following two projects:
 - the Okuna API: https://github.com/OkunaOrg/okuna-api
 - the Okuna app: https://github.com/OkunaOrg/okuna-app

which contain the source code of the Okuna social network.

**Comment by alsiPanda** [comment]
@jozsefsallai Thanks for the info. Any tentative date around which okuna plans to launch the website ?

**Comment by kitlu007** [comment]
The user interface looks nice. When will be the website code be available @jozsefsallai 

Also the list of features of the platform ?

**Comment by jozsefsallai** [comment]
The web version is not ready for the public yet and we can't promise an ETA either. We will definitely let you know when the web version becomes public.

> Also the list of features of the platform ?

The platform is still under heavy development, so features get added on a regular basis. So far, the Okuna platform can provide things like text/photo/video/link posts, communities, rich privacy and customization settings, circles, lists, a connection and a follow system, and more. Private messaging is **not** currently available but it's on our roadmap.

If you want an invite to experience everything yourself, let me know!

**Comment by kitlu007** [comment]
@jozsefsallai yes my email Id is 

kitlu007@gmail.com

**Comment by kitlu007** [comment]
@jozsefsallai thanks for the invite. I've joined in. Really loved the app. Would like to build on top of it. Possible to share the website code as well on git ? , I know I'm asking for a little bit too much. But still.

**Comment by lifenautjoe** [comment]
There is no exact date yet for the web app version. We're currently hands on it to launch in the upcoming weeks. Stay tuned to our twitter account. Once we go live, you should find the matching repo here https://twitter.com/OkunaSocial

**Comment by jozsefsallai** [comment]
> Possible to share the website code as well on git ?
Everything we do is open-source and available in this organization. If you mean the source code of the web version, it will, too, be available on Github when we feel it's ready for the public's eye.

**Comment by lifenautjoe** [comment]
In regards to building on top of, of course, the code is open-source. However do keep in mind that its a AGPL 3.0 license. 

You can read more on it here https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)

**Comment by kitlu007** [comment]
@lifenautjoe sure. I know about the licence. Do I need to release the code every now and then in an interval or can do it once its launch ready ?

**Comment by lifenautjoe** [comment]
> ... when you distribute, publish or serve (i.e. through a web portal) modified or derivative software...

Therefore as soon as the code is running on the internet. It also has to be kept up to date from then on-wards.

This is mostly to make sure an enterprise doesn't take this and resells it.

**Comment by kitlu007** [comment]
@lifenautjoe Undertood. Will work with you guys closely.

**Comment by gieljnssns** [comment]
@jozsefsallai
Can you also sent me an invite?

**Comment by sultanmyrza** [comment]
> The web version is not ready for the public yet and we can't promise an ETA either. We will definitely let you know when the web version becomes public.
> 
> > Also the list of features of the platform ?
> 
> The platform is still under heavy development, so features get added on a regular basis. So far, the Okuna platform can provide things like text/photo/video/link posts, communities, rich privacy and customization settings, circles, lists, a connection and a follow system, and more. Private messaging is **not** currently available but it's on our roadmap.
> 
> If you want an invite to experience everything yourself, let me know!

can you please send me invite too. 
sultanmyrza@gmail.com

**Comment by Komposten** [comment]
@gieljnssns @sultanmyrza I've sent a couple of my spare invites your way. 👍

**Comment by gieljnssns** [comment]
@Komposten 
Thanks for the invitation, but I'm stuk at accepting the guidelines, I can not click accept.
I'm on an iPhone, should I post an issue at https://github.com/OkunaOrg/okuna-app ?
![IMG_3964](https://user-images.githubusercontent.com/17234951/78669104-07f73080-78dc-11ea-8d99-28089cdb02bc.PNG)

**Comment by gieljnssns** [comment]
Sorry, I spoke to soon
When I go back and then use continue again, I had be be very fast to click at accept before it grayed out.

So tanks again...

**Comment by jozsefsallai** [comment]
Keep in mind that this issue is not about requesting invites! So please, don't spam it by asking for invitations :)

**Comment by sultanmyrza** [comment]
Okan app originally written in VueJs and rewritten with flutter am I right?

**Comment by jozsefsallai** [comment]
No, the app was always written in Flutter. The web version is written in Vue.
