### ISSUE TITLE
Better internationalization strategy

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-www#58]
The current json internationalization strategy doesnt work really well with large text, sometimes containing html. 

Explore and suggest alternatives. Perhaps something that works with gettext to use the same translation platform for the upcoming Openbook API.

**Comment by villzor** [comment]
Which problems are you experiencing with large text? Would you like to drop json translation all together? If so, please ignore my suggestion :)

I'm using [this package](https://github.com/dkfbasel/vuex-i18n/blob/master/src/vuex-i18n-store.js) which combines Vuex with internationalization (you'd have to adopt Vuex in order to use it though). 

What I find convenient is how it allows me to combine a pattern where store modules and translations are loaded together, making the structure a bit more modular. I use server-side rendering and basically followed the example from the docs implementing the "asyncdata"function on components. As the function returns a promise, I use it to lazy load translation files, like this: 
```
import moduleStore from '../../store/modules/module-store'
export default {
  asyncData ({ store, route, i18n, hydrate }) {
    store.registerModule('moduleStore ', moduleStore , { preserveState: hydrate });
    return new Promise((resolve, reject) => {
      import(`./locales/${i18n.locale()}`).then(result => {
        i18n.add(i18n.locale(), result.default);
        store.dispatch('moduleStore /fetchItem', route.params.id).then(() => {
            resolve();
        });
      }).catch(ex => reject(ex)); //language not found, reinvoke component with default language or warn user
    })
  },
```
Right now I'm facing a trade-off with the approach: either I force each /view-component to import localization files for the components it requires (sometimes making the asyncData function quite bloated), or moving this functionality into my reusable components. I don't know what would be better.

Sidenote is that vuex-router-sync went bananas on me when I implemented this, it tried to access a read-only property in some router-hook, I ended up removing it all together...

**Comment by lifenautjoe** [comment]
Hi @villzor ! Thanks for the suggestion!

We haven't tried Vuex i18n but the solution we currently have works similarly. We have en.js, es.js and more files like that which get dynamically loaded based on the user preferences. 

The issue we're facing is that every-time we change some text on the website, we have to do it for all other languages. Given that most of these translations were done by volunteers, we have to ask them to take a look again. 

However, the process for translation these texts is quite painful for them too. The .js translation file looks like

```js
 jobs: {
            title: 'Jobs',
            subtitle: 'Work with us.',
            exciting_adventure: 'We have embarked on one of the most exciting adventures for the digital world and we\'re looking for talented and passionate people to sail with us!',
            all_skills: 'Technology, design, marketing, finance, media, you name it.',
            need_your_help: 'Do you believe in <span class="has-text-primary"><strong class="has-text-primary">Open</strong>book</span>, a better future for social networks and humanity as a whole?',
            send_cv: 'Send us your CV and a motivation letter to  <a\n' +
            '                        href="mailto:jobs@open-book.org?subject=Job%20Application">jobs@open-book.org</a>.',
            look_forward: 'We look forward to meeting you !',
            colleagues: 'Who will you be working with?',
            meet_the_team: 'Meet the team'
        },
```

In the translation platform we use, http://lokalise.co, they see only the key of the JSON values together with a bunch of html on the other side to translate. I hope you can see the pain of the translators already and with larger chunks of text it's even worse.

For reference, [here's the en.js file](https://github.com/OpenbookOrg/openbook-org-www/blob/master/src/locale/en.js). 

So what we're looking for is a better way to do translations for volunteers. Perhaps something we could even automate. I personally like django does it with `gettext`. You use the "real" texts on the code, as `_('What is your name')` and it automatically extracts them with a tool on a file where you can upload to a collaborative translation platform and automatically update/remove translations and notify translators of this.

If you have some more ideas, always welcomed! 

Nice weekend! 👋

**Comment by villzor** [comment]
Aha, I misunderstood your problem! 

I had no plans for this evening so I thought I'd give it a try, [here is what I came up with](https://github.com/villzor/locale-parser). It's pretty bare-bones, but basically it connects to your git repository and performs a manual "git diff" algorithm between two commits, and compares the contents of your translation files. 

Right now I just assume en.js is your default language and that the developers add their language files there. Then upon commit, you just run the script and it outputs a result.json file containing:

- Subtractions: translation keys that were removed
- Substitutions: changes to existing keys and previous translations in other languages, including the previous key.
- Inconsistencies: missing language files.

Basically you get something like this:
```
    "subtitle": {
      "oldValue": "We want to build tech for <span class=\"has-text-primary\">good</span>.",
      "newValue": "Technology for a <span class=\"has-text-primary\">better tomorrow</span>.",
      "langDiff": {
        "de": "Wir wollen eine Plattform, die verwendet wird um  <span class=\"has-text-primary\"> Gutes </span> zu tun.",
        "es": "Queremos crear tecnología para <span class=\"has-text-primary\">bien</span>.",
        "fr": "Nous voulons construire un outil pour <span class=\"has-text-primary\">le bien</span>.",
        "hu": "Szeretnénk egy <span class='has-text-primary'>jóra törekvő</span> eszközt létrehozni.",
        "nl": "We willen een platform maken dat gebruikt wordt om <span class=\"has-text-primary\">goed</span> te doen.",
        "no": "Vi vil bygge et verktøy for <span class=\"has-text-primary\"> godt </span> ."
      }
    },
```

Obviously this would require some more work to get it working (e.g. create a revwalker for each translation file etc), but it wouldn't be too hard to fix. 

I don't know much about collaborative platforms though. It might be worth just hacking together something suited for your needs? I mean, basically you need to be able to extract out your localization files, store them in some backend so you can keep track of their state (if you change a a translation you'd want to mark it as dirty until a translator has updated it), and then just a html page where you show the translation (here you could parse html so translators just see the formatted language).

If you need help, let me know! Maybe I could sketch something up, would be fun to contribute, I really like your initiative with OpenBook! :)

**Comment by lifenautjoe** [comment]
Woah this is great villzor.

It’s a bit late now here (00:26) but Ive taken a quick look and looks like
we can do something with this :).

I’ll take a closer look tomorrow with the team and let you know how we’ll
proceed.

The translation platforms we’re looking into are lokalise.co and transifex
for now, there’s free demo accounts so in case you’re curious you can take
a look.

We will have to create a platform of our own to deal with crowdsourced
translations inside openbook but for now it doesn’t hurt to make as much
use of existing tech :).

Thanks for your time and contribution !

We’ll be talking soon again I’m sure :).


Cheers,
Joel.

**Comment by villzor** [comment]
Glad I could help! :)

**Comment by thadguidry** [comment]
@lifenautjoe use Weblate.  We did at OpenRefine ([see here](https://github.com/OpenRefine/OpenRefine/wiki/Translate-OpenRefine) and our code) and only had 1 minor annoyance as noted in this issue comment https://github.com/OpenRefine/OpenRefine/issues/1350#issuecomment-345758555

**Comment by lifenautjoe** [comment]
Done by the awesome @jozsefsallai ! We're now using CrowdIn for this!
