### ISSUE TITLE
Beta signup is possible multiple times which always updates the counter

### ISSUE THREAD

**Issue by Nils-Kolvenbach** [OkunaOrg/okuna-www#93]
I just subscribed to the beta waitlist and clicked on the success button by accident, seeing that the counter is updated for every click. The network tab revealed that the API is called too. Seems like the counter is updated on every click and not on every successful subscription. Of cause this could be fixed by just adding a check on `subscribeSuccessful` before calling `postToMailChimp()`, but a server side solution would be better in my opinion.

![Bildschirmfoto 2019-04-03 um 15 11 25](https://user-images.githubusercontent.com/2317940/55481481-ca096180-5622-11e9-86d2-1ceee6a1f87d.png)

While going through the [related component](https://github.com/OpenbookOrg/openbook-org-www/blob/master/src/views/home/components/beta-signup/beta-signup.vue) I noticed that there are quite a few code styling issues like indentation and `&nbsp;`'s.

Later this day I may have time to propose a change to this component.

**Comment by duichwer** [comment]
I think this issue can be closed after the merge of the PR?
